<template>
    <Line
                :chart-options="chartOptions"
                :chart-data="chartData"
                :chart-id="'chartId1'"
                :dataset-id-key="'datasetIdKey1'"
                :css-classes="cssClasses"
                :height="height"
        />
</template>
